# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

general {
    col.active_border = rgba(101315ee) rgba(101315ee) rgba(101315ee) rgba(798186ee) rgba(798186ee) rgba(798186ee) rgba(798186ee) rgba(798186ee) 90deg 
    col.inactive_border = rgb(1e1e1e)
    gaps_in = 4
    gaps_out = 5
    border_size = 2
}

group {
    col.border_active = rgba(798186ee) rgba(101315ee) rgba(101315ee) rgba(798186ee) 5deg
    col.border_inactive = rgb(101315)

    groupbar {
        col.active = rgba(79818688)
        col.inactive = rgba(101315aa)
        text_color = rgb(101315)
        text_color_inactive = rgba(798186aa)
    }
}

decoration {
    rounding = 6
    rounding_power = 3
      shadow {
      enabled = yes
      range = 16
      color = rgba(00000052)
    }
}

windowrule = match:class ^(vesktop|Vesktop)$, opacity 1.0 override, no_dim on
windowrule = match:class ^(code|VSCode|VSCodium)$, opacity 1.0 override, no_dim on
windowrule = match:class ^(chromium|Chromium|google-chrome|Brave|brave-browser)$, opacity 1.0 override, no_dim on