-- Generated by scripts/hypr2lua.
-- Source: /home/hancore/.config/omarchy/themes/solitude/hyprland.conf

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(101315ee)", "rgba(101315ee)", "rgba(101315ee)", "rgba(798186ee)", "rgba(798186ee)", "rgba(798186ee)", "rgba(798186ee)", "rgba(798186ee)" },
        angle = 90,
      },
      inactive_border = "rgb(1e1e1e)",
    },
    gaps_in = 4,
    gaps_out = 5,
    border_size = 2,
  },
  group = {
  col = {
    border_active = {
      colors = { "rgba(798186ee)", "rgba(101315ee)", "rgba(101315ee)", "rgba(798186ee)" },
      angle = 90,
    },
    border_inactive = "rgb(101315)",
  },
  groupbar = {
    col = {
      active = "rgba(79818688)",
      inactive = "rgba(101315aa)",
    },
    text_color = "rgb(101315)",
    text_color_inactive = "rgba(798186aa)",
  },
},
  decoration = {
    rounding = 6,
    rounding_power = 3,
    shadow = {
      enabled = true,
      range = 16,
      color = "rgba(00000052)",
    },
  },
})

hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(vesktop|Vesktop)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(code|VSCode|VSCodium)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(chromium|Chromium|google-chrome|Brave|brave-browser)$",
  },
})
