$color = rgba(6, 1, 20, 1)
$inner_color = rgba(6, 1, 20, 0.66)
$outer_color = rgba(170, 162, 206, 1)
$font_color = rgba(215, 219, 233, 1)
$placeholder_color = rgba(215, 219, 233, 0.7)
$check_color = rgba(186, 216, 255, 1)
