background            #060114
foreground            #D7DBE9

# black
color0  #060114
color8  #66656b

# red
color1  #9c8ba9
color9  #b39fc5

# green
color2  #a1c4e4
color10 #aedcff

# yellow
color3  #c4f6ff
color11 #bcfbff

# blue
color4  #757b9d
color12 #898fb9

# magenta
color5  #aaa2ce
color13 #c1b6ee

#cyan
color6  #bad8ff
color14 #caf0ff

#white
color7  #D7DBE9
color15 #f3f4ff


