-- Generated by hypr2lua-web.
-- Source: hyprland.conf

local activeBorderColor = {
  colors = { "rgba(9a9488ee)", "rgba(222220ee)" },
  angle = 45,
}

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
    },
    gaps_in = 2,
    gaps_out = 2,
    border_size = 2,
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
  decoration = {
    rounding = 0,
    shadow = {
      enabled = true,
      render_power = 3,
      range = 16,
      color = "rgba(00000052)",
    },
    blur = {
      enabled = true,
      size = 3,
      passes = 2,
    },
  },
})

hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(vesktop|Vesktop)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(code|VSCode|VSCodium)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(chromium|Chromium|google-chrome|Brave|brave-browser)$",
  },
})
