mode = "dark"

accent = "#9a724a"
selection = "#302c28"
muted = "#68584a"

background = "#191410"
dark_background = "#130f0c"
darker_background = "#0d0a08"
lighter_background = "#302c28"

foreground = "#afa89c"
dark_foreground = "#837d75"
light_foreground = "#bbb5ab"
bright_foreground = "#c3beb5"

red = "#c87a5c"
yellow = "#c4a64e"
orange = "#d08e74"
green = "#88ae52"
cyan = "#529298"
blue = "#9a724a"
magenta = "#8a7856"
brown = "#7d5546"

bright_red = "#d89268"
bright_yellow = "#d4ba60"
bright_green = "#98c45a"
bright_cyan = "#48a2aa"
bright_blue = "#ae795a"
bright_magenta = "#a08e66"
