mode = "dark"

accent = "#7dd2b8"
selection = "#252a27"
muted = "#595b5a"

background = "#171a18"
dark_background = "#121513"
darker_background = "#0d0f0e"
lighter_background = "#252a27"

foreground = "#d4d5d5"
dark_foreground = "#a0a3a3"
light_foreground = "#dedfdf"
bright_foreground = "#eeeeee"

red = "#d47c6b"
yellow = "#e0d480"
orange = "#aec282"
green = "#b8c082"
cyan = "#c5e8c5"
blue = "#7dd2b8"
magenta = "#b5c9a4"
brown = "#4f6c54"

bright_red = "#e89584"
bright_yellow = "#f2e590"
bright_green = "#cdd590"
bright_cyan = "#d8f5d8"
bright_blue = "#92e2c8"
bright_magenta = "#c8dab8"
