$color = rgba(23, 23, 23, 1)
$inner_color = rgba(23, 23, 23, 1)
$outer_color = rgba(174, 171, 148, 1)
$font_color = rgba(172, 171, 169, 1)
$placeholder_color = rgba(23, 23, 23, 1)
$check_color = rgba(242, 86, 35, 1)
