mode = "dark"

accent = "#2a7a80"
selection = "#1e1e1e"
muted = "#585553"

background = "#0f0f0f"
dark_background = "#0a0a0a"
darker_background = "#050505"
lighter_background = "#1e1e1e"

foreground = "#e0d8d0"
dark_foreground = "#b7a593"
light_foreground = "#e8e2dc"
bright_foreground = "#f4f2ef"

red = "#e6441a"
yellow = "#e68040"
orange = "#e6622d"
green = "#1a6b6e"
cyan = "#40b8b4"
blue = "#2a7a80"
magenta = "#c4753d"
brown = "#852c15"

bright_red = "#e66b40"
bright_yellow = "#e6a052"
bright_green = "#40c4c0"
bright_cyan = "#70e0dd"
bright_blue = "#52c9cd"
bright_magenta = "#e6b375"
