-- Generated by the Omarchy Workspace Layout plugin. Do not edit.
-- Your layouts and profiles live in ~/.config/omarchy/workspace-layout.json;
-- this file is rewritten from that document every time it changes.
--
-- Active profile: default

local W = _G.__omarchy_wsl
if not W then W = { registered = {}, rules = {} }; _G.__omarchy_wsl = W end
W.specs = {}

local function normalize(weights)
  local total = 0
  for i = 1, #weights do total = total + weights[i] end
  local out = {}
  if total <= 0 then
    for i = 1, #weights do out[i] = 100 / #weights end
    return out
  end
  for i = 1, #weights do out[i] = weights[i] * 100 / total end
  return out
end

local function orient(orientation, main_offset, main_size, cross_offset, cross_size)
  if orientation == "rows" then
    return { cross_offset, main_offset, cross_size, main_size }
  end
  return { main_offset, cross_offset, main_size, cross_size }
end

local function grid_rects(spec, n)
  local columns
  if spec.grid_columns and spec.grid_columns > 0 then
    columns = math.min(spec.grid_columns, n)
  else
    columns = math.ceil(math.sqrt(n))
  end
  local rows = math.ceil(n / columns)
  local rects = {}
  for row = 0, rows - 1 do
    local first = row * columns
    local in_row = math.min(columns, n - first)
    for col = 0, in_row - 1 do
      local right = (col == in_row - 1) and 1 or (col + 1) / in_row
      local bottom = (row == rows - 1) and 1 or (row + 1) / rows
      rects[#rects + 1] = { col / in_row, row / rows, right - col / in_row, bottom - row / rows }
    end
  end
  return rects
end

-- Widest slot first, so the first window lands in the main area rather than
-- in a sliver at the edge. Ties keep positional order. table.sort is not
-- stable in Lua, hence the explicit index tiebreak.
local function fill_order(weights)
  local index = {}
  for i = 1, #weights do index[i] = i end
  table.sort(index, function(a, b)
    if weights[a] ~= weights[b] then return weights[a] > weights[b] end
    return a < b
  end)
  return index
end

local function ratio_rects(spec, n)
  local weights = spec.weights
  local k = #weights
  local primary = {}
  local stack_at, stack_count = -1, 0

  if n <= k and spec.underfill == "hold" then
    for i = 1, k do primary[i] = weights[i] end
  elseif n <= k then
    local chosen = {}
    local priority = fill_order(weights)
    for i = 1, n do chosen[i] = priority[i] end
    table.sort(chosen)
    for i = 1, n do primary[i] = weights[chosen[i]] end
  elseif spec.overflow == "extend" then
    for i = 1, k do primary[i] = weights[i] end
    for i = k + 1, n do primary[i] = weights[k] end
  else
    for i = 1, k do primary[i] = weights[i] end
    stack_at = (spec.overflow == "first") and 1 or k
    stack_count = n - k + 1
  end

  primary = normalize(primary)

  local cells, cell_slot = {}, {}
  local offset = 0
  for slot = 1, #primary do
    local size = primary[slot] / 100
    if slot == #primary then size = 1 - offset end
    if slot == stack_at then
      for s = 0, stack_count - 1 do
        local sub_offset = s / stack_count
        local sub_size = (s == stack_count - 1) and (1 - sub_offset) or (1 / stack_count)
        cells[#cells + 1] = orient(spec.orientation, offset, size, sub_offset, sub_size)
        cell_slot[#cell_slot + 1] = slot
      end
    else
      cells[#cells + 1] = orient(spec.orientation, offset, size, 0, 1)
      cell_slot[#cell_slot + 1] = slot
    end
    offset = offset + size
  end

  local order
  if spec.fill == "order" then
    order = {}
    for i = 1, #primary do order[i] = i end
  else
    order = fill_order(primary)
  end

  local rects = {}
  for i = 1, #order do
    for c = 1, #cells do
      if cell_slot[c] == order[i] then rects[#rects + 1] = cells[c] end
    end
  end
  -- Under "hold" there are more cells than windows; the surplus are the
  -- empty slots, and they are last because the list is in fill order.
  while #rects > n do table.remove(rects) end
  return rects
end

function W.rects(spec, n)
  if n <= 0 then return {} end
  if spec.kind == "grid" then return grid_rects(spec, n) end
  return ratio_rects(spec, n)
end

-- Convert fractions to pixels by rounding the *edges*, not the sizes, so
-- neighbouring windows always share an exact boundary and no seam of dead
-- pixels opens up between them.
function W.place(id, ctx)
  local n = #ctx.targets
  if n == 0 then return end
  local spec = W.specs[id]
  if not spec then return end
  local a = ctx.area
  local rects = W.rects(spec, n)
  for i = 1, n do
    local r = rects[i]
    if r then
      local x0 = math.floor(a.w * r[1] + 0.5)
      local y0 = math.floor(a.h * r[2] + 0.5)
      local x1 = math.floor(a.w * (r[1] + r[3]) + 0.5)
      local y1 = math.floor(a.h * (r[2] + r[4]) + 0.5)
      ctx.targets[i]:place({ x = a.x + x0, y = a.y + y0, w = x1 - x0, h = y1 - y0 })
    end
  end
end

-- Hyprland refuses a second registration under the same name, and this file
-- is re-run on every config reload, so registration is remembered for the
-- life of the compositor. Behaviour still updates: the closure reads
-- W.specs, which the reload has just replaced.
function W.register(id)
  local name = "omarchy-wsl-" .. id
  if W.registered[name] then return end
  W.registered[name] = true
  hl.layout.register(name, {
    recalculate = function(ctx) W.place(id, ctx) end,
    layout_msg = function(ctx, msg)
      if ctx then W.place(id, ctx) end
      return true
    end,
  })
end

-- Workspace rules accumulate: adding a second rule for a workspace does not
-- retire the first. Keep the handle so the previous rule can be disabled,
-- otherwise switching profiles would pile up dead rules that still win.
function W.set_workspace(ws, layout)
  local previous = W.rules[ws]
  if previous then pcall(function() previous:set_enabled(false) end) end
  W.rules[ws] = hl.workspace_rule({ workspace = ws, layout = layout })
end

-- Nothing re-tiles a workspace just because its spec changed, so ask the
-- active layout to lay itself out again. Errors on a workspace running a
-- built-in layout, which has no idea what this message means.
function W.relayout()
  pcall(function() hl.dispatch(hl.dsp.layout("relayout")) end)
end

W.specs["even"] = { kind = "ratio", orientation = "columns", overflow = "extend", fill = "largest", underfill = "rescale", grid_columns = 0, weights = { 50, 50 } }
W.specs["focus"] = { kind = "ratio", orientation = "columns", overflow = "last", fill = "largest", underfill = "hold", grid_columns = 0, weights = { 25, 50, 25 } }
W.specs["main"] = { kind = "ratio", orientation = "columns", overflow = "last", fill = "largest", underfill = "rescale", grid_columns = 0, weights = { 60, 40 } }
W.specs["main-right"] = { kind = "ratio", orientation = "columns", overflow = "first", fill = "largest", underfill = "rescale", grid_columns = 0, weights = { 40, 60 } }
W.specs["golden"] = { kind = "ratio", orientation = "columns", overflow = "last", fill = "largest", underfill = "rescale", grid_columns = 0, weights = { 61.8, 38.2 } }
W.specs["thirds"] = { kind = "ratio", orientation = "columns", overflow = "extend", fill = "largest", underfill = "rescale", grid_columns = 0, weights = { 100 } }
W.specs["wide-centre"] = { kind = "ratio", orientation = "columns", overflow = "last", fill = "largest", underfill = "hold", grid_columns = 0, weights = { 20, 60, 20 } }
W.specs["stacked"] = { kind = "ratio", orientation = "rows", overflow = "last", fill = "largest", underfill = "rescale", grid_columns = 0, weights = { 50, 50 } }
W.specs["grid"] = { kind = "grid", orientation = "columns", overflow = "extend", fill = "largest", underfill = "rescale", grid_columns = 0, weights = { 25, 18.75, 18.75, 37.5 } }
W.specs["two-rows-four-columns"] = { kind = "grid", orientation = "columns", overflow = "extend", fill = "largest", underfill = "rescale", grid_columns = 4, weights = { 25, 25, 25, 25 } }
W.specs["custom"] = { kind = "ratio", orientation = "columns", overflow = "extend", fill = "largest", underfill = "rescale", grid_columns = 0, weights = { 33.33, 33.33, 16.67, 16.67 } }

W.register("even")
W.register("focus")
W.register("main")
W.register("main-right")
W.register("golden")
W.register("thirds")
W.register("wide-centre")
W.register("stacked")
W.register("grid")
W.register("two-rows-four-columns")
W.register("custom")

W.set_workspace("1", "lua:omarchy-wsl-golden")
W.set_workspace("2", "lua:omarchy-wsl-two-rows-four-columns")
W.set_workspace("3", "lua:omarchy-wsl-two-rows-four-columns")
W.set_workspace("4", "lua:omarchy-wsl-two-rows-four-columns")
W.set_workspace("5", "dwindle")
W.set_workspace("6", "dwindle")
W.set_workspace("7", "dwindle")
W.set_workspace("8", "dwindle")
W.set_workspace("9", "dwindle")
W.set_workspace("10", "dwindle")
