-- Generated by hypr2lua-web.
-- Source: hyprland.conf

hl.config({
  general = {
    col = {
      active_border = "rgba(43464Eee)",
      inactive_border = "rgb(090E13)",
    },
    gaps_in = 4,
    gaps_out = 5,
    border_size = 2,
  },
  group = {
    col = {
      border_active = "rgba(43464Eee)",
      border_inactive = "rgb(090E13)",
    },
    groupbar = {
      col = {
        active = "rgba(090E1399)",
        inactive = "rgba(393B4488)",
      },
      text_color = "rgb(c4746e)",
      text_color_inactive = "rgba(938aa9ee)",
    },
  },
  decoration = {
    rounding = 3,
    rounding_power = 3,
    shadow = {
      enabled = true,
      range = 16,
      color = "rgba(00000066)",
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("easeOutExpo", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.curve("softSnap", { type = "bezier", points = { { 0.2, 0.8 }, { 0.2, 1 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 3,
  bezier = "easeOutExpo",
  style = "popin 80%",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 3,
  bezier = "easeOutExpo",
  style = "popin 80%",
})
hl.animation({
  leaf = "fadeIn",
  enabled = true,
  speed = 2,
  bezier = "softSnap",
})
hl.animation({
  leaf = "fadeOut",
  enabled = true,
  speed = 2,
  bezier = "softSnap",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 4,
  bezier = "softSnap",
  style = "slide",
})
hl.animation({
  leaf = "layers",
  enabled = true,
  speed = 3,
  bezier = "softSnap",
  style = "fade",
})
