$color = rgba(9, 14, 19, 1.0)
$inner_color = rgba(9, 14, 19, 1.0)
$outer_color = rgba(67, 70, 78, 1.0)
$font_color = rgba(197, 201, 199, 1.0)
$placeholder_color = rgba(197, 201, 199, 0.7)
$check_color = rgba(142, 164, 162, 1.0)