# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

general {
    col.active_border = rgba(43464Eee)
    col.inactive_border = rgb(090E13)
    gaps_in = 4
    gaps_out = 5
    border_size = 2
}

group {
    col.border_active = rgba(43464Eee)
    col.border_inactive = rgb(090E13)

    groupbar {
        col.active = rgba(090E1399)
        col.inactive = rgba(393B4488)
        text_color = rgb(c4746e)
        text_color_inactive = rgba(938aa9ee)
    }
}

decoration {
    rounding = 3
    rounding_power = 3
      shadow {
      enabled = yes
      range = 16
      color = rgba(00000066)
    }
}

animations {
    enabled = yes

    bezier = easeOutExpo, 0.16, 1, 0.3, 1
    bezier = softSnap, 0.2, 0.8, 0.2, 1

    animation = windows, 1, 3, easeOutExpo, popin 80%
    animation = windowsOut, 1, 3, easeOutExpo, popin 80%
    
    animation = fadeIn, 1, 2, softSnap
    animation = fadeOut, 1, 2, softSnap
    
    animation = workspaces, 1, 4, softSnap, slide
    
    animation = layers, 1, 3, softSnap, fade
}
