$color = rgba(13, 19, 25, 1)
$inner_color = rgba(13, 19, 25, 0.66)
$outer_color = rgba(224, 161, 84, 1)
$font_color = rgba(242, 236, 205, 1)
$placeholder_color = rgba(242, 236, 205, 0.7)
$check_color = rgba(235, 227, 108, 1)
