-- Generated by scripts/hypr2lua.
-- Source: /home/hancore/.config/omarchy/themes/ryu/hyprland.conf

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(525e5aee)", "rgba(525e5aee)", "rgba(8B9388ee)", "rgba(8B9388ee)", "rgba(da614eee)", "rgba(da614eee)" },
        angle = 90,
      },
      inactive_border = "rgb(050505)",
    },
    gaps_in = 4,
    gaps_out = 5,
    border_size = 2,
  },
  group = {
    col = {
      border_active = "rgba(525e5aee)",
      border_inactive = "rgb(050505)",
    },
    groupbar = {
      col = {
        active = "rgba(05050599)",
        inactive = "rgba(8B938888)",
      },
      text_color = "rgb(da614e)",
      text_color_inactive = "rgba(525e5aee)",
    },
  },
  decoration = {
    rounding = 3,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 4,
      range = 16,
      color = "rgba(5, 5, 5, .7)",
    },
  },
})