$color = rgba(5, 5, 5, 1)
$inner_color = rgba(5, 5, 5, 1)
$outer_color = rgba(82, 94, 90, 1)
$font_color = rgba(214, 208, 197, 1)
$placeholder_color = rgba(214, 208, 197, 0.7)
$check_color = rgba(194, 164, 109, 1)
