[tools]
codex = "latest"
gemini = { version = "latest", allow_builds = ["@github/keytar", "node-pty"] }
gh = "latest"
go = "latest"
node = "26.7.0"
python = "latest"

[settings.upgrade]
auto_prune = false
